# Generated by Django 5.2.7 on 2025-12-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("SALES", "Sales User")],
                default="ADMIN",
                max_length=20,
            ),
        ),
    ]
